services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - wallet
  web:
    build: web/
    # image: node:latest
    # entrypoint: sleep infinity
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
      # - ./web/auth.ts:/app/auth.ts
      # - ./web/middleware.ts:/app/middleware.ts
      - ./web/package.json:/app/package.json
      - ./web/package-lock.json:/app/package-lock.json
    depends_on:
      - mongo
  wallet:
    build: wallet/
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./wallet/app:/app/app
      - ./wallet/public:/app/public
      - ./wallet/tailwind.config.ts:/app/tailwind.config.ts
      - ./wallet/package.json:/app/package.json
      - ./wallet/package-lock.json:/app/package-lock.json
      - ./wallet/next.config.js:/app/next.config.js
  mongo:
    image: mongo:7
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27011:27017
    volumes:
      - ./db:/data/db
      - ./bkp:/dump
